added follower/following list
mann-c/CMPT276Project pull request #28
Opened 2020-07-19 19:52 UTC by JenniceLee0318

2020-07-19 20:31 UTC, sanjayalwani reviewed
This is a start, we'll need to include the follower/following list in the user page, note that we've also queried the friends table in our get user profile request so we have that available on initialization.
Also I think the follower following naming for user profile is the other way around, people who are following the user are the "followers" and people who are being followed by the user are the people the user is "following".

2020-07-21 01:04 UTC, mann-c requested changes
why did you undo all of the changes to index.js that sanjay made on thursday?

2020-07-21 01:04 UTC, mann-c commented on index.js
> +    `SELECT * FROM users WHERE login='${username}'`,
why did you change this, parameters should be used

2020-07-21 01:04 UTC, mann-c commented on index.js
> +          `INSERT INTO users VALUES('${username}','${first_name}','${last_name}','${city}','','${password}')`,
parameters should be used

2020-07-21 01:04 UTC, mann-c commented on index.js
> +  var query = `select * from restaurants where id=${uid}`;
should be using parameters

2020-07-23 04:24 UTC, closed without merging