added 2 tests for user login
mann-c/CMPT276Project pull request #29
Opened 2020-07-20 05:37 UTC by jaskaran27177

and removed the register restaurant feature along with added a message for users who cant login

2020-07-20 23:52 UTC, sanjayalwani commented on index.js
> +      return res.redirect("/mainpage", {messages:"THE USERNAME OR PASSOWORD IS INCORRECT"});
spelling error

2020-07-20 23:52 UTC, sanjayalwani commented on index.js
> +      return res.render("pages/mainpage", {messages:"THE USERNAME OR PASSOWORD IS INCORRECT"}); //This does not work and crashes our app when reached
spelling error

2020-07-21 00:59 UTC, mann-c requested changes

2020-07-21 00:59 UTC, mann-c commented on index.js
> +app.get("/getall",(req,res)=>{
should this not authenticate the user?

2020-07-22 06:02 UTC, closed without merging