added user.ejs
mann-c/CMPT276Project pull request #6
Opened 2020-07-07 04:28 UTC by JenniceLee0318

2020-07-08 00:37 UTC, sanjayalwani commented on index.js
> +var fs = require("fs");
Where do you use url or fs? Can we remove this

2020-07-08 00:37 UTC, sanjayalwani commented on index.js
> +app.set('pages', path.join(__dirname, 'pages'));
what is pages for isn't everything in views?

2020-07-08 00:37 UTC, sanjayalwani commented on index.js
> +}));
why bodyparser urlencoded and express urlencoded one with extended as false and one as true

2020-07-09 00:26 UTC, sanjayalwani requested changes

2020-07-09 00:26 UTC, sanjayalwani commented on index.js
> +var fs = require("fs");
where do you use this

2020-07-09 00:26 UTC, sanjayalwani commented on index.js
> +// });
clean up comments

2020-07-09 05:33 UTC, mann-c requested changes

2020-07-09 05:33 UTC, mann-c commented on package.json
>      "express": "^4.17.1",
delete this file from the pull request

2020-07-09 05:33 UTC, mann-c commented on views/pages/index.ejs
>  <div class="jumbotron text-center">
delete this file from the merge request

2020-07-09 06:13 UTC, mann-c approved these changes

2020-07-09 06:25 UTC, sanjayalwani approved these changes

2020-07-09 06:26 UTC, merged